version: '3'
services:
  webapp:
    build: .
    ports:
      - 80:3000
    links:
      - mongo
    environment:
      - APP_PORT=3000
      - APP_HOST=0.0.0.0
      - APP_NAME=Express Boilerplate
      - LOG_LEVEL=error
      - MYSQL_HOST=localhost
      - MYSQL_USER=root
      - MYSQL_PASS=root
      - MYSQL_NAME=database
      - MYSQL_PORT=3306
      - MONGO_URL=mongodb://mongo:27017/databse

  mongo:
    image: mongo
    ports:
    - "27017:27017"
